version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 16 with nvm..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - . "$NVM_DIR/nvm.sh"
      - nvm install 16
      - nvm use 16
      - node -v
      - npm install -g newman
      - yum install -y jq

  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - newman run PetStoreAPI.postman_collection.json --environment PetStoreAPIEnvironment.postman_environment.json -r junit

reports:
  JUnitReports:
    files:
      - '**/*'
    base-directory: '02postman/newman'
