version: 0.2

phases:
  install:
    commands:
      - echo "Installing custom Node.js version 16 ..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - nvm install 16
      - nvm use 16
      - npm install -g newman
      - yum install -y jq

  pre_build:
    commands:
      # - aws s3 cp "s3://${S3_BUCKET}/..." ./02postman/
      # - cd ./02postman
      # - ./update-postman-env-file.sh

  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      - newman run PetStoreAPI.postman_collection.json --environment PetStoreAPIEnvironment.postman_environment.json -r junit

reports:
  JUnitReports:
    files:
      - '**/*'
    base-directory: '02postman/newman'
